# Generated by Django 3.2.4 on 2021-06-30 02:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelFile',
            fields=[
                ('image', models.ImageField(upload_to='documents/')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('result', models.IntegerField(blank=True, null=True)),
                ('proba', models.FloatField(default=0.0)),
                ('registered_date', models.DateField(default=datetime.date(2021, 6, 30))),
                ('animal_name', models.CharField(blank=True, max_length=10, null=True)),
                ('information', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
