# Generated by Django 3.2.4 on 2021-07-12 07:36

import datetime
from django.db import migrations, models
import send_image_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelFile',
            fields=[
                ('image', models.ImageField(upload_to=send_image_app.models._user_profile_avator_upload_to)),
                ('animal_id', models.AutoField(primary_key=True, serialize=False)),
                ('result', models.IntegerField(blank=True, null=True)),
                ('proba', models.FloatField(default=0.0)),
                ('registered_date', models.DateField(default=datetime.date(2021, 7, 12))),
                ('animal_name', models.CharField(blank=True, max_length=10, null=True)),
                ('information', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
