# Generated by Django 3.2.4 on 2021-06-24 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_image_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelfile',
            name='proba',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='modelfile',
            name='result',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modelfile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
