# Generated by Django 3.2.4 on 2021-06-24 02:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_image_app', '0002_auto_20210624_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelfile',
            name='registered_date',
            field=models.DateField(default=datetime.date(2021, 6, 24)),
        ),
    ]
