# Generated by Django 3.2.4 on 2021-06-28 05:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_image_app', '0003_modelfile_registered_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelfile',
            name='information',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='modelfile',
            name='registered_date',
            field=models.DateField(default=datetime.date(2021, 6, 28)),
        ),
    ]
