# Generated by Django 3.2.4 on 2021-06-28 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_image_app', '0004_auto_20210628_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelfile',
            name='animal_name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
